meta_product_name: "Dcrypt"
meta_title: "Dcrypt - your one stop shop for crypto data"
meta_description: "Get the latest info from CT on your favorite coins, check the latest price action and get the latest news."
meta_image: "cover.png" # should exist in `app/assets/images/`
